# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{acts_as_list_mongoid}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-07-06}
  s.description = %q{Make your Mongoid model acts as a list. This acts_as extension provides the capabilities for sorting and reordering a number of objects in a list.
      The instances that take part in the list should have a +position+ field of type Integer.}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".DS_Store",
     ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "acts_as_list_mongoid.gemspec",
     "example/example.rb",
     "init.rb",
     "lib/.DS_Store",
     "lib/acts_as_list_mongoid.rb",
     "lib/init.rb",
     "lib/mongoid/acts_as_list.rb",
     "model/embedded_item.rb",
     "spec/.rspec",
     "spec/acts_as_list/embedded_item_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rails/acts_as_list}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{acts_as_list for Mongoid}
  s.test_files = [
    "spec/acts_as_list/embedded_item_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta.15"])
      s.add_runtime_dependency(%q<mongoid_embedded_helper>, [">= 0.2.3"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.15"])
      s.add_dependency(%q<mongoid_embedded_helper>, [">= 0.2.3"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.15"])
    s.add_dependency(%q<mongoid_embedded_helper>, [">= 0.2.3"])
  end
end

